---
- name: Get all users from MAAS
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: List all MAAS users
      maas.maas.user_info:
        maas_url: "{{ maas_url_secret }}"
        maas_api_key: "{{ maas_api_key_secret }}"
      register: users_result
      failed_when: users_result.failed is defined and users_result.failed

    - name: Display MAAS users list
      ansible.builtin.debug:
        var: users_result.result
      when: users_result.failed is not defined or not users_result.failed
